version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=23757898Sql!
    container_name: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/news_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=23757898Sql!
    image: 'news-project:latest'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    container_name: app
